version: '3.8'

services:
  web:
    build: .
    container_name: visitor-id-app
    ports:
      - "5000:5000"
#    volumes:
#      - ./app:/app
    environment:
      - FLASK_ENV=development
    restart: always

volumes:
  sqlite_data:
    driver: local
